import { Resend } from "resend";
import { z } from "zod";
import { getBrief } from "@/lib/chatbot/corpus";
import type { ArkaConfig } from "@/lib/chatbot/env";

/**
 * An enquiry from the Arka widget, validated and emailed to sales.
 *
 * The visitor types their own details into a form; the model never extracts
 * them. Where the lead came from is taken from the request, never the model:
 * the page they asked on, and the referrer and campaign tags the widget
 * recorded when they first arrived (lib/chatbot/entry.ts). The request's own
 * Referer header is not used — the form posts from inside the site, so it is
 * always the site's own page.
 *
 * Plain-text email only. The transcript is visitor-written text, and plain
 * text cannot carry markup into anyone's mail client.
 */

/*
  Kept as close to what was typed as possible, because a callback number that
  was "corrected" into a different number is a lost lead.

  An 11-digit number starting with 0 is either a mobile with its trunk prefix
  or a landline with its STD code — 0821 is Mysuru — and the digits cannot
  tell the two apart. Both are dialable as written, so the 0 stays.
*/
function normalisePhone(raw: string): string {
  const trimmed = raw.trim();
  const digits = trimmed.replace(/\D/g, "");
  if (digits.length === 12 && digits.startsWith("91")) return digits.slice(2);
  if (trimmed.startsWith("+")) return `+${digits}`;
  return digits;
}

const phone = z
  .string()
  .max(24)
  .transform(normalisePhone)
  .refine(
    (v) =>
      /^[6-9]\d{9}$/.test(v) || // Indian mobile
      /^0\d{10}$/.test(v) || // with a trunk prefix or an STD code
      /^\+\d{8,15}$/.test(v), // international
    {
      message:
        "Enter a number we can call: a 10-digit mobile, a landline with its STD code, or an international number starting with +.",
    },
  );

const turn = z.object({
  role: z.enum(["user", "assistant"]),
  content: z.string().max(2_000),
});

export const leadSchema = z
  .object({
    /** Generated by the widget per submission; the idempotency key. */
    leadId: z.string().uuid(),
    conversationId: z.string().uuid(),
    name: z.string().trim().min(2, "Please enter your name.").max(80),
    phone,
    email: z
      .string()
      .trim()
      .max(120)
      .optional()
      .transform((v) => (v ? v : undefined))
      .pipe(z.string().email("That email address doesn't look right.").optional()),
    project: z.string().trim().max(40).optional(),
    note: z.string().trim().max(500).optional(),
    consent: z.literal(true, { message: "Please agree before sending." }),
    pagePath: z.string().startsWith("/").max(200),
    source: z
      .object({
        referrer: z.string().max(500),
        landing: z.string().max(500),
      })
      .strict()
      .optional(),
    transcript: z.array(turn).max(24),
    /** Honeypot. A person never sees this field; a bot fills it. */
    website: z.string().max(0).optional(),
  })
  .strict();

export type Lead = z.infer<typeof leadSchema>;

export type Provenance = {
  origin: string;
  userAgent: string | null;
  receivedAt: Date;
};

export type SendResult =
  | { ok: true; emailId: string }
  | { ok: false; code: "unconfigured" | "timeout" | "rejected" | "failed" };

const SEND_TIMEOUT_MS = 10_000;

const IST = new Intl.DateTimeFormat("en-IN", {
  timeZone: "Asia/Kolkata",
  dateStyle: "medium",
  timeStyle: "short",
});

function projectName(slug: string | undefined): string | undefined {
  return slug ? getBrief(slug)?.name : undefined;
}

/**
 * The external site that sent the visitor, or null for direct and internal
 * arrivals. Origin and path only: referrer query strings can carry search
 * terms and, on some sites, email addresses.
 */
export function externalReferrer(raw: string | undefined, origin: string): string | null {
  if (!raw) return null;
  try {
    const url = new URL(raw);
    if (!/^https?:$/.test(url.protocol) || url.origin === origin) return null;
    return `${url.origin}${url.pathname}`;
  } catch {
    return null;
  }
}

const CLICK_IDS: Record<string, string> = {
  gclid: "Google Ads",
  fbclid: "Facebook or Instagram",
  msclkid: "Microsoft Ads",
};

/**
 * The landing path with only its campaign tags kept, plus a readable summary.
 * Other query parameters are dropped for the same reason as above.
 */
export function campaignOf(landing: string | undefined): {
  landing: string | null;
  campaign: string | null;
} {
  if (!landing?.startsWith("/")) return { landing: null, campaign: null };
  const url = new URL(landing, "https://placeholder.invalid");
  const kept = new URLSearchParams();
  for (const [key, value] of url.searchParams) {
    if (key.startsWith("utm_")) kept.set(key, value.slice(0, 80));
  }
  const tags = ["utm_source", "utm_medium", "utm_campaign"]
    .map((k) => kept.get(k))
    .filter(Boolean);
  const clicked = Object.entries(CLICK_IDS)
    .filter(([k]) => url.searchParams.has(k))
    .map(([, name]) => `${name} ad click`);
  const query = kept.toString();
  return {
    landing: `${url.pathname}${query ? `?${query}` : ""}`,
    campaign: [...tags, ...clicked].join(" / ") || null,
  };
}

/** Single-line, so a value can never start a new header or section. */
function oneLine(value: string): string {
  return value.replace(/[\r\n]+/g, " ").trim();
}

export function composeLeadEmail(lead: Lead, from: Provenance) {
  const project = projectName(lead.project);
  const subject = `New enquiry — ${project ?? "General"} — via Arka`;

  const rows: [string, string | undefined][] = [
    ["Name", oneLine(lead.name)],
    ["Phone", lead.phone],
    ["Email", lead.email],
    ["Project", project ?? "Not specified"],
    ["Note", lead.note ? oneLine(lead.note) : undefined],
  ];

  const arrived = externalReferrer(lead.source?.referrer, from.origin);
  const { landing, campaign } = campaignOf(lead.source?.landing);

  const where: [string, string | null][] = [
    ["Asked on", `${from.origin}${lead.pagePath}`],
    ["Arrived from", arrived ?? (lead.source ? "Direct, or a link with no referrer" : "Not recorded")],
    ["Campaign", campaign ? oneLine(campaign) : null],
    ["Landing page", landing ? `${from.origin}${oneLine(landing)}` : null],
    ["Received", `${IST.format(from.receivedAt)} IST`],
    ["Device", from.userAgent ? oneLine(from.userAgent).slice(0, 160) : null],
    ["Conversation", lead.conversationId],
  ];

  const transcript = lead.transcript.length
    ? lead.transcript
        .map((t) => `${t.role === "user" ? "Visitor" : "Arka"}: ${oneLine(t.content)}`)
        .join("\n")
    : "(The visitor used the form without chatting.)";

  const text = [
    "A new enquiry came in through Arka, the website assistant.",
    "",
    ...rows.filter(([, v]) => v).map(([k, v]) => `${k.padEnd(9)} ${v}`),
    "",
    "WHERE IT CAME FROM",
    ...where.filter(([, v]) => v).map(([k, v]) => `${k.padEnd(13)} ${v}`),
    "",
    "CONVERSATION",
    transcript,
  ].join("\n");

  return { subject, text };
}

let resend: Resend | undefined;

export async function sendLead(
  config: ArkaConfig,
  lead: Lead,
  from: Provenance,
): Promise<SendResult> {
  if (!config.lead.ready || !config.lead.resendKey || !config.lead.from) {
    return { ok: false, code: "unconfigured" };
  }
  resend ??= new Resend(config.lead.resendKey);

  const { subject, text } = composeLeadEmail(lead, from);

  let timer: ReturnType<typeof setTimeout> | undefined;
  const timeout = new Promise<"timeout">((resolve) => {
    timer = setTimeout(() => resolve("timeout"), SEND_TIMEOUT_MS);
  });

  try {
    const outcome = await Promise.race([
      resend.emails.send(
        {
          from: config.lead.from,
          to: config.lead.inbox,
          replyTo: lead.email,
          subject,
          text,
        },
        // A double-tap or a retry sends one email, not two.
        { idempotencyKey: lead.leadId },
      ),
      timeout,
    ]);

    if (outcome === "timeout") return { ok: false, code: "timeout" };
    if (outcome.error) return { ok: false, code: "rejected" };
    return { ok: true, emailId: outcome.data.id };
  } catch {
    // Network failure inside the SDK. The route logs it by code; the error
    // itself may carry request details and is not passed on.
    return { ok: false, code: "failed" };
  } finally {
    clearTimeout(timer);
  }
}
